require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - Vagrantfile

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
